#!/bin/bash

# This is a test! Hello World!

git submodule update --init --recursive
cp dotbot/tools/git-submodule/install .

cat << EOF
All done!

To install these dotfiles, run:

./install --plugin-dir dotbot-plugins/omnipkg

Have fun!
EOF
