# Disable the blank line at the start of the prompt
# add_newline = false

[cmd_duration]
min_time = 5000
style = ""
format = '[\[ $duration \]]($style)'

[username]
show_always = false
style_user = ""
style_root = ""
format = '[\[ $user \]]($style)'

[sudo]
disabled = false
symbol = ""
style = ""
format = '[\[ $symbol \]]($style)'

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = ""
format = "[ $path ]($style)"

[directory.substitutions]
"Documents/Programming" = " "
"Documents/Configuration" = "漣 "
"Documents" = " "
"Downloads" = " "
"Music" = "ﱘ "
"Pictures" = " "
"Desktop" = " "

[git_branch]
symbol = ""
style = ""
format = '[\[ $symbol $branch \]]($style)'

[git_commit]
style = ""
format = '[\[ $hash$tag \]]($style)'

[git_state]

[git_metrics]

[git_status]
style = ""
format = '[\[ $all_status$ahead_behind \]]($style)'


[java]
symbol = ""

[python]
symbol = ""
pyenv_version_name = true

[rust]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = true
